# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-20 01:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.URLField(default='http://placehold.it/750x300', verbose_name='封面图片'),
        ),
    ]
